spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: prod
  messages:
    basename: i18n/messages

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 47.100.92.117:22122


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB